import argparse

from python_server import fsm_server


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='FSM server')
    parser.add_argument('fsm_code_file', help='Python source file generated by the translator')
    args = parser.parse_args()
    fsm_server.run(args.fsm_code_file)
